bar:
    acl:
        grants:
            full_control:
                - s3_admin
            read:
                - alice
                - bob
            write:
                - bob
        owner:
            display_name: S3 Admin
            id: s3_admin
    acl_type: present
    bucket_type: present
    lifecycle_rules:
        - cur_ver_expiration_days: 30
          id: DeleteOldDone
          non_cur_ver_expiration_days: -1
          prefix: done/
          status: enabled
        - cur_ver_expiration_days: 365
          id: DeleteOldErrors
          non_cur_ver_expiration_days: -1
          prefix: errors/
          status: enabled
    lifecycle_type: present
    versioning: disabled
baz:
    acl:
        grants:
            full_control: []
            read: []
            write: []
        owner:
            display_name: ""
            id: ""
    acl_type: new
    bucket_type: new
    lifecycle_rules: []
    lifecycle_type: new
    versioning: disabled
foo:
    acl:
        grants:
            full_control:
                - s3_admin
                - alice
            read:
                - bob
            write: []
        owner:
            display_name: ""
            id: ""
    acl_type: new
    bucket_type: new
    lifecycle_rules:
        - cur_ver_expiration_days: 14
          id: DeleteOldDone
          non_cur_ver_expiration_days: 7
          prefix: done/
          status: enabled
        - cur_ver_expiration_days: 365
          id: DeleteOldErrors
          non_cur_ver_expiration_days: 5
          prefix: errors/
          status: enabled
    lifecycle_type: new
    versioning: enabled
