bar:
  acl:
    grants:
      full_control:
      - s3_admin
      read:
      - alice
      - bob
      write:
      - bob
    owner:
      display_name: S3 Admin
      id: s3_admin
  lifecycle_rules:
  - cur_ver_expiration_days: 30
    id: DeleteOldDone
    non_cur_ver_expiration_days: -1
    prefix: done/
    status: enabled
  - cur_ver_expiration_days: 365
    id: DeleteOldErrors
    non_cur_ver_expiration_days: -1
    prefix: errors/
    status: enabled
  versioning: enabled
baz:
  acl:
    grants:
      full_control: []
      read: []
      write: []
    owner:
      display_name: ""
      id: ""
  lifecycle_rules: []
  versioning: suspended
foo:
  acl:
    grants:
      full_control:
      - alice
      - s3_admin
      read:
      - bob
      write:
      - s3_admin
    owner:
      display_name: S3 Admin
      id: s3_admin
  lifecycle_rules:
  - cur_ver_expiration_days: 31
    id: DeleteOldDone
    non_cur_ver_expiration_days: -1
    prefix: done/
    status: enabled
  - cur_ver_expiration_days: 365
    id: DeleteOldErrors
    non_cur_ver_expiration_days: -1
    prefix: errors/
    status: disabled
  versioning: suspended
